sudo: false
language: python
python:
  - 2.7
  - 3.6

install: pip install tox-travis
script: tox

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      python: 3.6
      script: tox -e flake8

    - stage: deploy
      python: 3.6
      script: tox -e sphinx
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/_build/html
        on:
          branch: master
