sudo: false
language: python
python:
  - 2.7
  - 3.6

install: pip install tox-travis
script: tox

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: 3.6
      script: tox -e flake8
